"""
dashboard/dashboard_app.py
---------------------------
Streamlit Dashboard — Cyber Attack Monitoring System

OVERVIEW:
This dashboard provides real-time visualization of cyber attacks detected by the
CyberWatch autonomous monitoring system. It displays threat metrics, attack timelines,
IP analysis, and detailed alert information.

DATA SOURCES (Priority Order):
1. CIC-IDS 2017 Dataset (data/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv)
2. AlertAgent Logs (logs/alerts.csv) - Generated by the pipeline
3. Demo Data (Synthetic) - Fallback if no real data available

FEATURES:
- Real-time threat monitoring with auto-refresh
- Time-window filtering (1-24 hours)
- Threat level filtering (ALERT/WATCH/ALL)
- Attack timeline visualization
- Attack type distribution
- Top threat IPs ranking
- Recent alerts feed
- CSV export functionality

USAGE:
    streamlit run dashboard/dashboard_app.py

REQUIREMENTS:
    - streamlit >= 1.32.0
    - pandas >= 2.0.0
    - plotly >= 5.18.0
    - numpy >= 1.24.0

AUTHOR: CyberWatch Team
VERSION: 1.0
"""

# ══════════════════════════════════════════════════════════════════════════════
# IMPORTS
# ══════════════════════════════════════════════════════════════════════════════

import streamlit as st          # Web dashboard framework
import pandas as pd             # Data manipulation and analysis
import numpy as np              # Numerical operations
import random                   # Random data generation for demo mode
from datetime import datetime, timedelta, timezone  # Timestamp handling
from pathlib import Path        # File path operations
import sys                      # System path manipulation

# Add parent directory to path to import custom modules
sys.path.insert(0, str(Path(__file__).parent.parent))

# ══════════════════════════════════════════════════════════════════════════════
# STREAMLIT PAGE CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
# Must be the first Streamlit command - configures page layout and appearance

st.set_page_config(
    page_title="CyberWatch — Attack Monitor",  # Browser tab title
    page_icon="🛡️",                             # Browser tab icon
    layout="wide",                              # Use full screen width
    initial_sidebar_state="expanded",           # Show sidebar by default
)

# ══════════════════════════════════════════════════════════════════════════════
# CUSTOM CSS STYLING
# ══════════════════════════════════════════════════════════════════════════════
# Cyber-themed dark mode design with custom fonts, colors, and animations
# Uses Google Fonts: Syne (headings) and Share Tech Mono (monospace)

st.markdown("""
<style>
  /* Import custom fonts from Google Fonts */
  @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Syne:wght@400;700;800&display=swap');

  /* Global styles - dark cyber theme */
  html, body, [class*="css"] {
    font-family: 'Syne', sans-serif;
    background-color: #080c14;  /* Deep dark blue background */
    color: #c8d8e8;             /* Light blue-gray text */
  }

  /* ─────────────────────────────────────────────────────────────────────────
     HEADER SECTION
     ───────────────────────────────────────────────────────────────────────── */
  .cyber-header {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 24px 0 8px;
    border-bottom: 1px solid #1a2a3a;
    margin-bottom: 28px;
  }
  .cyber-title {
    font-size: 28px;
    font-weight: 800;
    letter-spacing: -0.5px;
    color: #e8f4ff;
  }
  .cyber-title span { color: #00d4ff; }  /* Cyan accent for "Watch" */
  .cyber-subtitle {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    letter-spacing: 2px;
    text-transform: uppercase;
    margin-top: 2px;
  }
  
  /* Animated status indicator dot */
  .status-dot {
    width: 10px; height: 10px;
    background: #00ff88;        /* Green = system active */
    border-radius: 50%;
    box-shadow: 0 0 8px #00ff88;
    animation: pulse 2s ease-in-out infinite;
    flex-shrink: 0;
  }
  @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.4} }

  /* ─────────────────────────────────────────────────────────────────────────
     METRIC CARDS (Alerts, Watches, IPs, Top Attack)
     ───────────────────────────────────────────────────────────────────────── */
  .metric-row { display: flex; gap: 16px; margin-bottom: 28px; flex-wrap: wrap; }
  .metric-card {
    flex: 1; min-width: 140px;
    background: #0d1520;
    border: 1px solid #1a2a3a;
    border-radius: 10px;
    padding: 18px 20px;
    position: relative;
    overflow: hidden;
  }
  
  /* Colored top border for each metric type */
  .metric-card::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
  }
  .metric-card.red::before   { background: #ff4560; }  /* Alerts = red */
  .metric-card.amber::before { background: #ffb731; }  /* Watches = amber */
  .metric-card.green::before { background: #00e396; }  /* Top Attack = green */
  .metric-card.blue::before  { background: #00d4ff; }  /* IPs = blue */
  
  .metric-label {
    font-family: 'Share Tech Mono', monospace;
    font-size: 10px;
    color: #4a6a8a;
    letter-spacing: 2px;
    text-transform: uppercase;
    margin-bottom: 8px;
  }
  .metric-value {
    font-size: 34px;
    font-weight: 800;
    line-height: 1;
    color: #e8f4ff;
  }
  
  /* Color-coded metric values */
  .metric-card.red   .metric-value { color: #ff4560; }
  .metric-card.amber .metric-value { color: #ffb731; }
  .metric-card.green .metric-value { color: #00e396; }
  .metric-card.blue  .metric-value { color: #00d4ff; }
  
  .metric-sub {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    margin-top: 6px;
  }

  /* ─────────────────────────────────────────────────────────────────────────
     ALERT ROWS (Recent alerts feed)
     ───────────────────────────────────────────────────────────────────────── */
  .alert-row {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 12px 16px;
    border-radius: 8px;
    margin-bottom: 8px;
    border: 1px solid transparent;
    font-family: 'Share Tech Mono', monospace;
    font-size: 12px;
  }
  
  /* Different styling for ALERT vs WATCH level threats */
  .alert-row.ALERT {
    background: rgba(255,69,96,0.08);   /* Red tint for high-severity */
    border-color: rgba(255,69,96,0.25);
  }
  .alert-row.WATCH {
    background: rgba(255,183,49,0.06);  /* Amber tint for medium-severity */
    border-color: rgba(255,183,49,0.2);
  }
  
  /* Threat level badge */
  .badge {
    padding: 3px 10px;
    border-radius: 4px;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 1px;
    flex-shrink: 0;
  }
  .badge.ALERT { background: #ff4560; color: #fff; }
  .badge.WATCH { background: #ffb731; color: #080c14; }
  
  /* Alert row content styling */
  .ip-text { color: #00d4ff; min-width: 130px; }
  .attack-text { color: #e8f4ff; min-width: 130px; text-transform: capitalize; }
  .conf-text { color: #4a6a8a; }
  .time-text { color: #4a6a8a; margin-left: auto; }

  /* ─────────────────────────────────────────────────────────────────────────
     SECTION HEADERS
     ───────────────────────────────────────────────────────────────────────── */
  .section-title {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    letter-spacing: 3px;
    text-transform: uppercase;
    margin: 28px 0 14px;
    display: flex;
    align-items: center;
    gap: 10px;
  }
  /* Horizontal line after section title */
  .section-title::after {
    content: '';
    flex: 1;
    height: 1px;
    background: #1a2a3a;
  }

  /* ─────────────────────────────────────────────────────────────────────────
     IP TABLE (Top threat IPs)
     ───────────────────────────────────────────────────────────────────────── */
  .ip-table { width: 100%; border-collapse: collapse; }
  .ip-table td, .ip-table th {
    padding: 10px 12px;
    text-align: left;
    font-family: 'Share Tech Mono', monospace;
    font-size: 12px;
    border-bottom: 1px solid #1a2a3a;
  }
  .ip-table th { color: #4a6a8a; font-size: 10px; letter-spacing: 2px; }
  .ip-table td { color: #c8d8e8; }
  .ip-table td:first-child { color: #00d4ff; }  /* Highlight IP addresses */
  
  /* Threat level bar visualization */
  .threat-bar {
    height: 4px;
    border-radius: 2px;
    background: linear-gradient(90deg, #ff4560, #ffb731);
  }

  /* ─────────────────────────────────────────────────────────────────────────
     STREAMLIT COMPONENT OVERRIDES
     ───────────────────────────────────────────────────────────────────────── */
  .stApp { background-color: #080c14; }
  section[data-testid="stSidebar"] { 
    background-color: #0a1018; 
    border-right: 1px solid #1a2a3a; 
  }
  .stSelectbox label, .stSlider label, .stCheckbox label { 
    color: #4a6a8a !important; 
    font-family: 'Share Tech Mono', monospace; 
    font-size: 11px; 
    letter-spacing: 1px; 
  }
  div[data-testid="stMetric"] { display: none; }  /* Hide default Streamlit metrics */
  h1,h2,h3 { color: #e8f4ff !important; }
</style>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# DATA LOADING FUNCTIONS
# ══════════════════════════════════════════════════════════════════════════════

# File paths for data sources
CSV_PATH = Path("logs/alerts.csv")  # AlertAgent output logs
CICIDS_PATH = Path("data/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv")  # CIC-IDS dataset

def load_demo_data() -> pd.DataFrame:
    """
    Generate realistic synthetic alert data for demonstration purposes.
    
    This function creates fake but realistic-looking cyber attack data when no
    real data sources are available. Used as a fallback to ensure the dashboard
    always has something to display.
    
    Returns:
        pd.DataFrame: Synthetic threat data with columns:
            - timestamp: When the threat occurred
            - level: ALERT or WATCH
            - ip: Source IP address
            - attack_type: Type of attack (brute_force, port_scan, etc.)
            - confidence: Detection confidence (0.0-1.0)
            - url: Targeted URL
            - status_code: HTTP status code
            - rules: Triggered detection rules
    
    Data Characteristics:
        - 120 total events over 6 hours
        - 28% attack rate (rest filtered out)
        - Mix of ALERT and WATCH level threats
        - Realistic IP addresses and attack patterns
    """
    random.seed(42)  # Reproducible random data
    np.random.seed(42)

    # Predefined IP pools for realistic data
    attack_ips = ["192.168.0.21", "203.0.113.5", "45.33.32.156", "198.20.69.74"]
    normal_ips = [f"10.0.0.{i}" for i in range(1, 12)]
    attack_types = ["brute_force", "port_scan", "web_attack", "sql_injection", "ddos"]

    rows = []
    base = datetime.now() - timedelta(hours=6)  # Start 6 hours ago

    for i in range(120):
        # Generate timestamp with some randomness
        ts   = base + timedelta(minutes=i * 3 + random.randint(0, 2))
        
        # 28% chance of attack
        is_attack = random.random() < 0.28
        ip    = random.choice(attack_ips) if is_attack else random.choice(normal_ips)
        
        # Determine threat level (ALERT = high confidence, WATCH = medium)
        level = "ALERT" if (is_attack and random.random() > 0.4) else ("WATCH" if is_attack else None)
        
        # Skip non-threats (normal traffic)
        if not level:
            continue
            
        rows.append({
            "timestamp"  : ts,
            "level"      : level,
            "ip"         : ip,
            "attack_type": random.choice(attack_types) if is_attack else "unknown",
            "confidence" : round(random.uniform(0.65, 0.99) if level == "ALERT" else random.uniform(0.3, 0.65), 2),
            "url"        : random.choice(["/login", "/admin", "/wp-login.php", "/api/data", "/phpmyadmin"]),
            "status_code": random.choice([401, 403, 404, 200]),
            "rules"      : random.choice(["brute_force,off_hours", "suspicious_agent", "high_error_rate", ""]),
        })

    return pd.DataFrame(rows)


@st.cache_data(ttl=10)  # Cache for 10 seconds to improve performance
def load_data() -> pd.DataFrame:
    """
    Load threat data with priority-based source selection.
    
    Data Source Priority:
        1. CIC-IDS 2017 Dataset (if available) - Real network attack data
        2. AlertAgent CSV logs (if available) - Pipeline-generated alerts
        3. Demo data (fallback) - Synthetic data for testing
    
    Returns:
        pd.DataFrame: Threat data with standardized columns:
            - timestamp (datetime, tz-naive UTC)
            - level (str): ALERT or WATCH
            - ip (str): Source IP address
            - attack_type (str): Attack classification
            - confidence (float): Detection confidence 0.0-1.0
            - url (str): Targeted URL
            - status_code (int): HTTP status code
            - rules (str): Comma-separated detection rules
    
    Encoding Handling:
        Tries multiple encodings (utf-8, latin-1, cp1252) to handle
        Windows-encoded CSV files that may contain non-UTF-8 characters.
    
    Timezone Handling:
        All timestamps are normalized to tz-naive UTC for consistent
        filtering and comparison operations.
    """
    
    # Priority 1: CIC-IDS dataset (real network attack data)
    if CICIDS_PATH.exists():
        try:
            from dashboard.cicids_loader import load_cicids_for_dashboard
            df = load_cicids_for_dashboard(str(CICIDS_PATH))
            print(f"[Dashboard] Loaded {len(df)} threats from CIC-IDS dataset")
            return df
        except Exception as e:
            st.warning(f"Failed to load CIC-IDS dataset: {e}. Falling back to alerts.csv")
    
    # Priority 2: AlertAgent logs (pipeline output)
    if CSV_PATH.exists():
        # Try multiple encodings to handle Windows CSV files
        for enc in ("utf-8", "latin-1", "cp1252"):
            try:
                df = pd.read_csv(CSV_PATH, encoding=enc)
                break
            except UnicodeDecodeError:
                continue
        
        # Parse timestamps and normalize to tz-naive UTC
        df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)
        df["timestamp"] = df["timestamp"].dt.tz_localize(None)  # Strip timezone
        
        print(f"[Dashboard] Loaded {len(df)} alerts from logs/alerts.csv")
        return df
    
    # Priority 3: Demo data (fallback)
    print("[Dashboard] Using demo data (no real data sources found)")
    return load_demo_data()


# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR CONTROLS
# ══════════════════════════════════════════════════════════════════════════════
# User controls for filtering and refreshing data

with st.sidebar:
    # Dashboard branding
    st.markdown("""
    <div style='font-family:"Share Tech Mono",monospace; font-size:11px; color:#4a6a8a;
                letter-spacing:2px; text-transform:uppercase; padding:16px 0 24px;'>
        🛡️ &nbsp;CyberWatch v1.0
    </div>
    """, unsafe_allow_html=True)

    # Filter controls
    show_level = st.selectbox("Threat level", ["ALL", "ALERT only", "WATCH only"])
    show_hours = st.slider("Time window (hours)", 1, 24, 6)  # Default: last 6 hours
    auto_refresh = st.checkbox("Auto-refresh (10s)", value=False)
    
    st.markdown("---")
    
    # Pipeline status indicators (static - shows all agents as active)
    st.markdown("""
    <div style='font-family:"Share Tech Mono",monospace; font-size:10px; color:#2a3a4a; line-height:2;'>
    PIPELINE STATUS<br>
    <span style='color:#00ff88'>● </span>Collector<br>
    <span style='color:#00ff88'>● </span>Analyzer<br>
    <span style='color:#00ff88'>● </span>ThreatAgent<br>
    <span style='color:#00ff88'>● </span>AlertAgent<br>
    </div>
    """, unsafe_allow_html=True)

    # Auto-refresh logic
    if auto_refresh:
        import time
        time.sleep(10)  # Wait 10 seconds
        st.rerun()      # Reload the entire dashboard

    # Manual refresh button
    if st.button("🔄  Refresh data"):
        st.cache_data.clear()  # Clear cached data
        st.rerun()             # Reload dashboard


# ══════════════════════════════════════════════════════════════════════════════
# DATA LOADING AND FILTERING
# ══════════════════════════════════════════════════════════════════════════════

# Load data from selected source (CIC-IDS, logs, or demo)
df = load_data()

# DEBUG: Uncomment to show data loading stats in sidebar
# st.sidebar.markdown("---")
# st.sidebar.markdown(f"**Data loaded:** {len(df)} rows")
# st.sidebar.markdown(f"**Time range:** {df['timestamp'].min()} to {df['timestamp'].max()}")

# Ensure timestamps are parsed correctly
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

# Normalize timezone: Convert all timestamps to tz-naive UTC
# This prevents "Cannot compare tz-naive and tz-aware datetime" errors
if df["timestamp"].dt.tz is not None:
    df["timestamp"] = df["timestamp"].dt.tz_convert("UTC").dt.tz_localize(None)

# Calculate time window cutoff (e.g., "show last 6 hours")
cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(hours=show_hours)

# DEBUG: Track rows before filtering
df_before_filter = len(df)

# Filter by time window
df = df[df["timestamp"] >= cutoff]

# DEBUG: Uncomment to show filtering stats
# st.sidebar.markdown(f"**After time filter:** {len(df)} rows (cutoff: {cutoff})")

# Filter by threat level (ALERT, WATCH, or ALL)
if show_level == "ALERT only":
    df = df[df["level"] == "ALERT"]
elif show_level == "WATCH only":
    df = df[df["level"] == "WATCH"]

# Sort by most recent first
df = df.sort_values("timestamp", ascending=False)


# ══════════════════════════════════════════════════════════════════════════════
# DASHBOARD HEADER
# ══════════════════════════════════════════════════════════════════════════════
# Displays title, status indicator, and current UTC time

st.markdown(f"""
<div class="cyber-header">
  <div class="status-dot"></div>  <!-- Animated green dot = system active -->
  <div>
    <div class="cyber-title">Cyber<span>Watch</span></div>
    <div class="cyber-subtitle">Autonomous Attack Detection &nbsp;·&nbsp; Live Monitor &nbsp;·&nbsp; {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC</div>
  </div>
</div>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# KEY METRICS CARDS
# ══════════════════════════════════════════════════════════════════════════════
# Four metric cards showing: Alerts, Watches, Unique IPs, Top Attack Type

# Calculate metrics from filtered data
alerts  = len(df[df["level"] == "ALERT"])   # High-confidence threats
watches = len(df[df["level"] == "WATCH"])   # Medium-confidence threats
uniq_ips = df["ip"].nunique() if "ip" in df.columns else 0  # Unique attacker IPs
top_attack = df["attack_type"].value_counts().idxmax() if len(df) and "attack_type" in df.columns else "—"

# Render metric cards with custom HTML/CSS
st.markdown(f"""
<div class="metric-row">
  <!-- ALERT-level threats (red card) -->
  <div class="metric-card red">
    <div class="metric-label">🚨 &nbsp;Alerts</div>
    <div class="metric-value">{alerts}</div>
    <div class="metric-sub">high confidence attacks</div>
  </div>
  
  <!-- WATCH-level threats (amber card) -->
  <div class="metric-card amber">
    <div class="metric-label">👁 &nbsp;Watches</div>
    <div class="metric-value">{watches}</div>
    <div class="metric-sub">suspicious activity</div>
  </div>
  
  <!-- Unique IP addresses (blue card) -->
  <div class="metric-card blue">
    <div class="metric-label">🌐 &nbsp;Unique IPs</div>
    <div class="metric-value">{uniq_ips}</div>
    <div class="metric-sub">flagged sources</div>
  </div>
  
  <!-- Most common attack type (green card) -->
  <div class="metric-card green">
    <div class="metric-label">⚡ &nbsp;Top Attack</div>
    <div class="metric-value" style="font-size:18px; padding-top:6px">{top_attack.replace("_"," ").title()}</div>
    <div class="metric-sub">most common pattern</div>
  </div>
</div>
""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# VISUALIZATION SECTION 1: CHARTS ROW
# ══════════════════════════════════════════════════════════════════════════════
# Two-column layout: Attack Timeline (left) and Attack Types (right)

# ── Charts row ───────────────────────────────────────────
col1, col2 = st.columns([3, 2])  # 60/40 split

with col1:
    # ─────────────────────────────────────────────────────
    # ATTACK TIMELINE CHART (Stacked Bar Chart)
    # ─────────────────────────────────────────────────────
    # Shows ALERT and WATCH threats over time in 30-minute bins
    
    st.markdown('<div class="section-title">Attack timeline</div>', unsafe_allow_html=True)

    if len(df):
        # Group threats into 30-minute time bins
        df["hour_bin"] = df["timestamp"].dt.floor("30min")
        timeline = df.groupby(["hour_bin", "level"]).size().unstack(fill_value=0).reset_index()

        import plotly.graph_objects as go

        # Create stacked bar chart
        fig = go.Figure()
        
        # Add ALERT bars (red)
        if "ALERT" in timeline.columns:
            fig.add_trace(go.Bar(
                x=timeline["hour_bin"], y=timeline["ALERT"],
                name="ALERT", marker_color="#ff4560", opacity=0.9
            ))
        
        # Add WATCH bars (amber)
        if "WATCH" in timeline.columns:
            fig.add_trace(go.Bar(
                x=timeline["hour_bin"], y=timeline["WATCH"],
                name="WATCH", marker_color="#ffb731", opacity=0.7
            ))
        
        # Apply dark theme styling
        fig.update_layout(
            barmode="stack",  # Stack ALERT on top of WATCH
            plot_bgcolor="#080c14", paper_bgcolor="#080c14",
            font=dict(family="Share Tech Mono", color="#4a6a8a", size=11),
            xaxis=dict(gridcolor="#1a2a3a", tickformat="%H:%M"),
            yaxis=dict(gridcolor="#1a2a3a"),
            legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#c8d8e8")),
            margin=dict(l=0, r=0, t=10, b=0),
            height=220,
        )
        st.plotly_chart(fig, width='stretch')
    else:
        st.markdown('<p style="color:#2a3a4a; font-family:Share Tech Mono; font-size:12px;">No data in selected window</p>', unsafe_allow_html=True)

with col2:
    # ─────────────────────────────────────────────────────
    # ATTACK TYPES CHART (Donut Chart)
    # ─────────────────────────────────────────────────────
    # Shows distribution of attack types (brute_force, port_scan, etc.)
    
    st.markdown('<div class="section-title">Attack types</div>', unsafe_allow_html=True)

    if len(df) and "attack_type" in df.columns:
        # Get top 6 attack types
        type_counts = df["attack_type"].value_counts().head(6)

        # Create donut chart (pie chart with hole in center)
        fig2 = go.Figure(go.Pie(
            labels=[t.replace("_", " ").title() for t in type_counts.index],
            values=type_counts.values,
            hole=0.65,  # Donut hole size
            marker=dict(colors=["#ff4560","#00d4ff","#ffb731","#00e396","#a855f7","#f97316"]),
            textfont=dict(family="Share Tech Mono", size=10, color="#c8d8e8"),
        ))
        
        # Apply dark theme styling
        fig2.update_layout(
            plot_bgcolor="#080c14", paper_bgcolor="#080c14",
            showlegend=True,
            legend=dict(font=dict(family="Share Tech Mono", color="#4a6a8a", size=10), bgcolor="rgba(0,0,0,0)"),
            margin=dict(l=0, r=0, t=10, b=0),
            height=220,
        )
        st.plotly_chart(fig2, width='stretch')


# ══════════════════════════════════════════════════════════════════════════════
# VISUALIZATION SECTION 2: THREAT DETAILS ROW
# ══════════════════════════════════════════════════════════════════════════════
# Two-column layout: Top Threat IPs (left) and Recent Alerts (right)

# ── Top IPs ─────────────────────────────────────────────
col3, col4 = st.columns([2, 3])  # 40/60 split

with col3:
    # ─────────────────────────────────────────────────────
    # TOP THREAT IPs TABLE
    # ─────────────────────────────────────────────────────
    # Shows the most active attacker IP addresses with threat bars
    
    st.markdown('<div class="section-title">Top threat IPs</div>', unsafe_allow_html=True)
    
    if len(df) and "ip" in df.columns:
        # Count threats per IP and get top 8
        ip_counts = df.groupby("ip").size().sort_values(ascending=False).head(8)
        max_count = ip_counts.max()

        # Build HTML table rows
        rows_html = ""
        for ip, count in ip_counts.items():
            # Calculate threat bar width (0-100%)
            bar_w = int((count / max_count) * 100)
            rows_html += f"""
            <tr>
              <td>{ip}</td>
              <td>{count}</td>
              <td><div class="threat-bar" style="width:{bar_w}%"></div></td>
            </tr>"""

        # Render custom HTML table
        st.markdown(f"""
        <table class="ip-table">
          <tr><th>IP Address</th><th>Hits</th><th>Threat</th></tr>
          {rows_html}
        </table>""", unsafe_allow_html=True)

with col4:
    # ─────────────────────────────────────────────────────
    # RECENT ALERTS FEED
    # ─────────────────────────────────────────────────────
    # Shows the 15 most recent threats with color-coded badges
    
    st.markdown('<div class="section-title">Recent alerts</div>', unsafe_allow_html=True)
    
    recent = df.head(15)  # Get 15 most recent (already sorted by timestamp desc)
    
    for _, row in recent.iterrows():
        # Extract row data with fallbacks
        level     = str(row.get("level", "WATCH"))
        ip        = str(row.get("ip", "—"))
        attack    = str(row.get("attack_type", "—")).replace("_", " ")
        conf      = float(row.get("confidence", 0))
        ts        = row.get("timestamp")
        ts_str    = ts.strftime("%H:%M:%S") if pd.notna(ts) else "—"

        # Render alert row with custom HTML
        st.markdown(f"""
        <div class="alert-row {level}">
          <span class="badge {level}">{level}</span>
          <span class="ip-text">{ip}</span>
          <span class="attack-text">{attack.title()}</span>
          <span class="conf-text">conf: {conf:.0%}</span>
          <span class="time-text">{ts_str}</span>
        </div>""", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# RAW DATA TABLE (Expandable)
# ══════════════════════════════════════════════════════════════════════════════
# Full alert log with CSV export functionality

# ── Raw data table ───────────────────────────────────────
with st.expander("📋  Full alert log"):
    # Select columns to display (only if they exist in dataframe)
    display_cols = [c for c in ["timestamp","level","ip","attack_type","confidence","url","status_code","rules"] if c in df.columns]
    
    # Show first 200 rows in a scrollable table
    st.dataframe(df[display_cols].head(200), width='stretch', hide_index=True)
    
    # CSV export button
    if st.button("⬇  Export CSV"):
        st.download_button("Download", df.to_csv(index=False), "alerts_export.csv", "text/csv")


# ══════════════════════════════════════════════════════════════════════════════
# END OF DASHBOARD
# ══════════════════════════════════════════════════════════════════════════════
# 
# DASHBOARD ARCHITECTURE SUMMARY:
# 
# 1. DATA FLOW:
#    CIC-IDS CSV → cicids_loader.py → load_data() → Filtering → Visualizations
#    OR
#    logs/alerts.csv → load_data() → Filtering → Visualizations
#    OR
#    load_demo_data() → Filtering → Visualizations
# 
# 2. KEY COMPONENTS:
#    - Sidebar: User controls (filters, time window, refresh)
#    - Header: Title and status indicator
#    - Metrics: 4 KPI cards (Alerts, Watches, IPs, Top Attack)
#    - Charts: Timeline (bar) and Attack Types (donut)
#    - Tables: Top IPs and Recent Alerts feed
#    - Expander: Full data table with CSV export
# 
# 3. DATA REQUIREMENTS:
#    Required columns: timestamp, level, ip, attack_type, confidence
#    Optional columns: url, status_code, rules
# 
# 4. PERFORMANCE:
#    - Data cached for 10 seconds (@st.cache_data)
#    - Auto-refresh optional (10-second interval)
#    - Filters applied client-side (fast)
# 
# 5. CUSTOMIZATION:
#    - Modify CSS in the <style> block for appearance
#    - Adjust time bins in timeline chart (currently 30min)
#    - Change color scheme in metric cards and charts
#    - Add new visualizations using Plotly or Streamlit components
# 
# ══════════════════════════════════════════════════════════════════════════════

