"""
dashboard/app.py
----------------
Streamlit Dashboard — Cyber Attack Monitoring System

Run with:
    streamlit run dashboard/app.py

Reads from:
    logs/alerts.csv   — generated by AlertAgent
    (or uses built-in demo data if no CSV found)
"""

import streamlit as st
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))

# ── Page config ─────────────────────────────────────────
st.set_page_config(
    page_title="CyberWatch — Attack Monitor",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ───────────────────────────────────────────
st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Syne:wght@400;700;800&display=swap');

  html, body, [class*="css"] {
    font-family: 'Syne', sans-serif;
    background-color: #080c14;
    color: #c8d8e8;
  }

  /* Header */
  .cyber-header {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 24px 0 8px;
    border-bottom: 1px solid #1a2a3a;
    margin-bottom: 28px;
  }
  .cyber-title {
    font-size: 28px;
    font-weight: 800;
    letter-spacing: -0.5px;
    color: #e8f4ff;
  }
  .cyber-title span { color: #00d4ff; }
  .cyber-subtitle {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    letter-spacing: 2px;
    text-transform: uppercase;
    margin-top: 2px;
  }
  .status-dot {
    width: 10px; height: 10px;
    background: #00ff88;
    border-radius: 50%;
    box-shadow: 0 0 8px #00ff88;
    animation: pulse 2s ease-in-out infinite;
    flex-shrink: 0;
  }
  @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.4} }

  /* Metric cards */
  .metric-row { display: flex; gap: 16px; margin-bottom: 28px; flex-wrap: wrap; }
  .metric-card {
    flex: 1; min-width: 140px;
    background: #0d1520;
    border: 1px solid #1a2a3a;
    border-radius: 10px;
    padding: 18px 20px;
    position: relative;
    overflow: hidden;
  }
  .metric-card::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 2px;
  }
  .metric-card.red::before   { background: #ff4560; }
  .metric-card.amber::before { background: #ffb731; }
  .metric-card.green::before { background: #00e396; }
  .metric-card.blue::before  { background: #00d4ff; }
  .metric-label {
    font-family: 'Share Tech Mono', monospace;
    font-size: 10px;
    color: #4a6a8a;
    letter-spacing: 2px;
    text-transform: uppercase;
    margin-bottom: 8px;
  }
  .metric-value {
    font-size: 34px;
    font-weight: 800;
    line-height: 1;
    color: #e8f4ff;
  }
  .metric-card.red   .metric-value { color: #ff4560; }
  .metric-card.amber .metric-value { color: #ffb731; }
  .metric-card.green .metric-value { color: #00e396; }
  .metric-card.blue  .metric-value { color: #00d4ff; }
  .metric-sub {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    margin-top: 6px;
  }

  /* Alert rows */
  .alert-row {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 12px 16px;
    border-radius: 8px;
    margin-bottom: 8px;
    border: 1px solid transparent;
    font-family: 'Share Tech Mono', monospace;
    font-size: 12px;
  }
  .alert-row.ALERT {
    background: rgba(255,69,96,0.08);
    border-color: rgba(255,69,96,0.25);
  }
  .alert-row.WATCH {
    background: rgba(255,183,49,0.06);
    border-color: rgba(255,183,49,0.2);
  }
  .badge {
    padding: 3px 10px;
    border-radius: 4px;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 1px;
    flex-shrink: 0;
  }
  .badge.ALERT { background: #ff4560; color: #fff; }
  .badge.WATCH { background: #ffb731; color: #080c14; }
  .ip-text { color: #00d4ff; min-width: 130px; }
  .attack-text { color: #e8f4ff; min-width: 130px; text-transform: capitalize; }
  .conf-text { color: #4a6a8a; }
  .time-text { color: #4a6a8a; margin-left: auto; }

  /* Section headers */
  .section-title {
    font-family: 'Share Tech Mono', monospace;
    font-size: 11px;
    color: #4a6a8a;
    letter-spacing: 3px;
    text-transform: uppercase;
    margin: 28px 0 14px;
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .section-title::after {
    content: '';
    flex: 1;
    height: 1px;
    background: #1a2a3a;
  }

  /* IP table */
  .ip-table { width: 100%; border-collapse: collapse; }
  .ip-table td, .ip-table th {
    padding: 10px 12px;
    text-align: left;
    font-family: 'Share Tech Mono', monospace;
    font-size: 12px;
    border-bottom: 1px solid #1a2a3a;
  }
  .ip-table th { color: #4a6a8a; font-size: 10px; letter-spacing: 2px; }
  .ip-table td { color: #c8d8e8; }
  .ip-table td:first-child { color: #00d4ff; }
  .threat-bar {
    height: 4px;
    border-radius: 2px;
    background: linear-gradient(90deg, #ff4560, #ffb731);
  }

  /* Override Streamlit defaults */
  .stApp { background-color: #080c14; }
  section[data-testid="stSidebar"] { background-color: #0a1018; border-right: 1px solid #1a2a3a; }
  .stSelectbox label, .stSlider label, .stCheckbox label { color: #4a6a8a !important; font-family: 'Share Tech Mono', monospace; font-size: 11px; letter-spacing: 1px; }
  div[data-testid="stMetric"] { display: none; }
  h1,h2,h3 { color: #e8f4ff !important; }
</style>
""", unsafe_allow_html=True)


# ── Data loading ─────────────────────────────────────────

CSV_PATH = Path("logs/alerts.csv")

def load_demo_data() -> pd.DataFrame:
    """Generate realistic synthetic alert data for the demo."""
    random.seed(42)
    np.random.seed(42)

    attack_ips = ["192.168.0.21", "203.0.113.5", "45.33.32.156", "198.20.69.74"]
    normal_ips = [f"10.0.0.{i}" for i in range(1, 12)]
    attack_types = ["brute_force", "port_scan", "web_attack", "sql_injection", "ddos"]

    rows = []
    base = datetime.now() - timedelta(hours=6)

    for i in range(120):
        ts   = base + timedelta(minutes=i * 3 + random.randint(0, 2))
        is_attack = random.random() < 0.28
        ip    = random.choice(attack_ips) if is_attack else random.choice(normal_ips)
        level = "ALERT" if (is_attack and random.random() > 0.4) else ("WATCH" if is_attack else None)
        if not level:
            continue
        rows.append({
            "timestamp"  : ts,
            "level"      : level,
            "ip"         : ip,
            "attack_type": random.choice(attack_types) if is_attack else "unknown",
            "confidence" : round(random.uniform(0.65, 0.99) if level == "ALERT" else random.uniform(0.3, 0.65), 2),
            "url"        : random.choice(["/login", "/admin", "/wp-login.php", "/api/data", "/phpmyadmin"]),
            "status_code": random.choice([401, 403, 404, 200]),
            "rules"      : random.choice(["brute_force,off_hours", "suspicious_agent", "high_error_rate", ""]),
        })

    return pd.DataFrame(rows)


@st.cache_data(ttl=10)
def load_data() -> pd.DataFrame:
    if CSV_PATH.exists():
        for enc in ("utf-8", "latin-1", "cp1252"):
            try:
                df = pd.read_csv(CSV_PATH, encoding=enc)
                break
            except UnicodeDecodeError:
                continue
        df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)
        df["timestamp"] = df["timestamp"].dt.tz_localize(None)  # strip tz → naive UTC
        return df
    return load_demo_data()


# ── Sidebar ──────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style='font-family:"Share Tech Mono",monospace; font-size:11px; color:#4a6a8a;
                letter-spacing:2px; text-transform:uppercase; padding:16px 0 24px;'>
        🛡️ &nbsp;CyberWatch v1.0
    </div>
    """, unsafe_allow_html=True)

    show_level = st.selectbox("Threat level", ["ALL", "ALERT only", "WATCH only"])
    show_hours = st.slider("Time window (hours)", 1, 24, 6)
    auto_refresh = st.checkbox("Auto-refresh (10s)", value=False)
    st.markdown("---")
    st.markdown("""
    <div style='font-family:"Share Tech Mono",monospace; font-size:10px; color:#2a3a4a; line-height:2;'>
    PIPELINE STATUS<br>
    <span style='color:#00ff88'>● </span>Collector<br>
    <span style='color:#00ff88'>● </span>Analyzer<br>
    <span style='color:#00ff88'>● </span>ThreatAgent<br>
    <span style='color:#00ff88'>● </span>AlertAgent<br>
    </div>
    """, unsafe_allow_html=True)

    if auto_refresh:
        import time
        time.sleep(10)
        st.rerun()

    if st.button("🔄  Refresh data"):
        st.cache_data.clear()
        st.rerun()


# ── Load + filter ────────────────────────────────────────
df = load_data()
df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
# Normalize: strip timezone so comparison is always tz-naive
if df["timestamp"].dt.tz is not None:
    df["timestamp"] = df["timestamp"].dt.tz_convert("UTC").dt.tz_localize(None)
cutoff = datetime.now(timezone.utc).replace(tzinfo=None) - timedelta(hours=show_hours)
df = df[df["timestamp"] >= cutoff]

if show_level == "ALERT only":
    df = df[df["level"] == "ALERT"]
elif show_level == "WATCH only":
    df = df[df["level"] == "WATCH"]

df = df.sort_values("timestamp", ascending=False)


# ── Header ───────────────────────────────────────────────
st.markdown(f"""
<div class="cyber-header">
  <div class="status-dot"></div>
  <div>
    <div class="cyber-title">Cyber<span>Watch</span></div>
    <div class="cyber-subtitle">Autonomous Attack Detection &nbsp;·&nbsp; Live Monitor &nbsp;·&nbsp; {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC</div>
  </div>
</div>
""", unsafe_allow_html=True)


# ── Metric cards ─────────────────────────────────────────
alerts  = len(df[df["level"] == "ALERT"])
watches = len(df[df["level"] == "WATCH"])
uniq_ips = df["ip"].nunique() if "ip" in df.columns else 0
top_attack = df["attack_type"].value_counts().idxmax() if len(df) and "attack_type" in df.columns else "—"

st.markdown(f"""
<div class="metric-row">
  <div class="metric-card red">
    <div class="metric-label">🚨 &nbsp;Alerts</div>
    <div class="metric-value">{alerts}</div>
    <div class="metric-sub">high confidence attacks</div>
  </div>
  <div class="metric-card amber">
    <div class="metric-label">👁 &nbsp;Watches</div>
    <div class="metric-value">{watches}</div>
    <div class="metric-sub">suspicious activity</div>
  </div>
  <div class="metric-card blue">
    <div class="metric-label">🌐 &nbsp;Unique IPs</div>
    <div class="metric-value">{uniq_ips}</div>
    <div class="metric-sub">flagged sources</div>
  </div>
  <div class="metric-card green">
    <div class="metric-label">⚡ &nbsp;Top Attack</div>
    <div class="metric-value" style="font-size:18px; padding-top:6px">{top_attack.replace("_"," ").title()}</div>
    <div class="metric-sub">most common pattern</div>
  </div>
</div>
""", unsafe_allow_html=True)


# ── Charts row ───────────────────────────────────────────
col1, col2 = st.columns([3, 2])

with col1:
    st.markdown('<div class="section-title">Attack timeline</div>', unsafe_allow_html=True)

    if len(df):
        df["hour_bin"] = df["timestamp"].dt.floor("30min")
        timeline = df.groupby(["hour_bin", "level"]).size().unstack(fill_value=0).reset_index()

        import plotly.graph_objects as go

        fig = go.Figure()
        if "ALERT" in timeline.columns:
            fig.add_trace(go.Bar(
                x=timeline["hour_bin"], y=timeline["ALERT"],
                name="ALERT", marker_color="#ff4560", opacity=0.9
            ))
        if "WATCH" in timeline.columns:
            fig.add_trace(go.Bar(
                x=timeline["hour_bin"], y=timeline["WATCH"],
                name="WATCH", marker_color="#ffb731", opacity=0.7
            ))
        fig.update_layout(
            barmode="stack",
            plot_bgcolor="#080c14", paper_bgcolor="#080c14",
            font=dict(family="Share Tech Mono", color="#4a6a8a", size=11),
            xaxis=dict(gridcolor="#1a2a3a", tickformat="%H:%M"),
            yaxis=dict(gridcolor="#1a2a3a"),
            legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(color="#c8d8e8")),
            margin=dict(l=0, r=0, t=10, b=0),
            height=220,
        )
        st.plotly_chart(fig, width='stretch')
    else:
        st.markdown('<p style="color:#2a3a4a; font-family:Share Tech Mono; font-size:12px;">No data in selected window</p>', unsafe_allow_html=True)

with col2:
    st.markdown('<div class="section-title">Attack types</div>', unsafe_allow_html=True)

    if len(df) and "attack_type" in df.columns:
        type_counts = df["attack_type"].value_counts().head(6)

        fig2 = go.Figure(go.Pie(
            labels=[t.replace("_", " ").title() for t in type_counts.index],
            values=type_counts.values,
            hole=0.65,
            marker=dict(colors=["#ff4560","#00d4ff","#ffb731","#00e396","#a855f7","#f97316"]),
            textfont=dict(family="Share Tech Mono", size=10, color="#c8d8e8"),
        ))
        fig2.update_layout(
            plot_bgcolor="#080c14", paper_bgcolor="#080c14",
            showlegend=True,
            legend=dict(font=dict(family="Share Tech Mono", color="#4a6a8a", size=10), bgcolor="rgba(0,0,0,0)"),
            margin=dict(l=0, r=0, t=10, b=0),
            height=220,
        )
        st.plotly_chart(fig2, width='stretch')


# ── Top IPs ─────────────────────────────────────────────
col3, col4 = st.columns([2, 3])

with col3:
    st.markdown('<div class="section-title">Top threat IPs</div>', unsafe_allow_html=True)
    if len(df) and "ip" in df.columns:
        ip_counts = df.groupby("ip").size().sort_values(ascending=False).head(8)
        max_count = ip_counts.max()

        rows_html = ""
        for ip, count in ip_counts.items():
            bar_w = int((count / max_count) * 100)
            rows_html += f"""
            <tr>
              <td>{ip}</td>
              <td>{count}</td>
              <td><div class="threat-bar" style="width:{bar_w}%"></div></td>
            </tr>"""

        st.markdown(f"""
        <table class="ip-table">
          <tr><th>IP Address</th><th>Hits</th><th>Threat</th></tr>
          {rows_html}
        </table>""", unsafe_allow_html=True)

with col4:
    st.markdown('<div class="section-title">Recent alerts</div>', unsafe_allow_html=True)
    recent = df.head(15)
    for _, row in recent.iterrows():
        level     = str(row.get("level", "WATCH"))
        ip        = str(row.get("ip", "—"))
        attack    = str(row.get("attack_type", "—")).replace("_", " ")
        conf      = float(row.get("confidence", 0))
        ts        = row.get("timestamp")
        ts_str    = ts.strftime("%H:%M:%S") if pd.notna(ts) else "—"

        st.markdown(f"""
        <div class="alert-row {level}">
          <span class="badge {level}">{level}</span>
          <span class="ip-text">{ip}</span>
          <span class="attack-text">{attack.title()}</span>
          <span class="conf-text">conf: {conf:.0%}</span>
          <span class="time-text">{ts_str}</span>
        </div>""", unsafe_allow_html=True)


# ── Raw data table ───────────────────────────────────────
with st.expander("📋  Full alert log"):
    display_cols = [c for c in ["timestamp","level","ip","attack_type","confidence","url","status_code","rules"] if c in df.columns]
    st.dataframe(df[display_cols].head(200), width='stretch', hide_index=True)
    if st.button("⬇  Export CSV"):
        st.download_button("Download", df.to_csv(index=False), "alerts_export.csv", "text/csv")
